abspath = which('set_path');
pos = strfind(abspath, filesep); pos = pos(end);
abspath = abspath(1:pos - 1);
s = [[abspath,filesep,'expokit;']...
    [abspath,filesep,'Brusselator;']...
    [abspath,filesep,'Burgers;']...
    [abspath,filesep,'CUSP;']...
    [abspath,filesep,'DND;']...
    [abspath,filesep,'phipm;']];
path(s,path);